// Code generated by https://github.com/elias506/vk-sdk. DO NOT EDIT.
// For more information about errors see https://dev.vk.com/reference/errors

package vk_sdk

type Subcode int

const (
	TooManyCommunities             Subcode = 1
	UserReachedLinkedAccountsLimit Subcode = 1000
	ServiceUuidLinkWithAnotherUser Subcode = 1001
)

type ErrorCode int

const (
	// Error_Unknown Unknown error occurred.
	// Solution: Try again later.
	//  IsGlobal: true
	Error_Unknown ErrorCode = 1
	// Error_Disabled Application is disabled. Enable your application or use test mode.
	// Solution: You need to switch on the app in Settings (https://vk.com/editapp?id={Your API_ID} or use the TestMode (test_mode=1).
	//  IsGlobal: true
	Error_Disabled ErrorCode = 2
	// Error_Method Unknown method passed.
	// Solution: Check the method name: https://vk.com/dev/methods
	//  IsGlobal: true
	Error_Method ErrorCode = 3
	// Error_Signature Incorrect signature.
	// Solution: Check if the signature has been formed correctly: https://vk.com/dev/api_nohttps.
	//  IsGlobal: true
	Error_Signature ErrorCode = 4
	// Error_Auth User authorization failed.
	// Solution: Make sure that you use a correct TokenType (https://vk.com/dev/access_token).
	//  IsGlobal: true
	Error_Auth ErrorCode = 5
	// Error_TooMany Too many requests per second.
	// Solution: Decrease the request frequency or use the execute method. More details on frequency limits here: https://vk.com/dev/api_requests.
	//  IsGlobal: true
	Error_TooMany ErrorCode = 6
	// Error_Permission Permission to perform this action is denied.
	// Solution: Make sure that your have received required AccessPermission during the authorization (see https://vk.com/dev/permissions). You can do it with the VK.Account_GetAppPermissions method.
	//  IsGlobal: true
	Error_Permission ErrorCode = 7
	// Error_Request Invalid request.
	// May contain one of the listed subcodes: [ UserReachedLinkedAccountsLimit, ServiceUuidLinkWithAnotherUser ].
	// Solution: Check the request syntax (https://vk.com/dev/api_requests) and used parameters list (it can be found on a method description page).
	//  IsGlobal: true
	Error_Request ErrorCode = 8
	// Error_Flood Flood control.
	// Solution: You need to decrease the count of identical requests. For more efficient work you may use execute (https://vk.com/dev/execute) or JSONP (https://vk.com/dev/jsonp).
	//  IsGlobal: true
	Error_Flood ErrorCode = 9
	// Error_Server Internal server error.
	// Solution: Try again later.
	//  IsGlobal: true
	Error_Server ErrorCode = 10
	// Error_EnabledInTest In test mode application should be disabled or user should be authorized.
	// Solution: Switch the app off in Settings: https://vk.com/editapp?id={Your API_ID}.
	//  IsGlobal: true
	Error_EnabledInTest ErrorCode = 11
	// Error_Compile Unable to compile code.
	//  IsGlobal: false
	Error_Compile ErrorCode = 12
	// Error_Runtime Runtime error occurred during code invocation.
	//  IsGlobal: false
	Error_Runtime ErrorCode = 13
	// Error_Captcha Captcha needed.
	// Solution: Work with this error is explained in detail on https://vk.com/dev/captcha_error.
	//  IsGlobal: true
	Error_Captcha ErrorCode = 14
	// Error_Access Access denied.
	// Solution: Make sure that you use correct identifiers and the content is available for the user in the full version of the site.
	//  IsGlobal: true
	Error_Access ErrorCode = 15
	// Error_AuthHttps HTTP authorization failed.
	// Solution: To avoid this error check if a user has the 'Use secure connection' option enabled with the VK.Account_GetInfo method.
	//  IsGlobal: true
	Error_AuthHttps ErrorCode = 16
	// Error_AuthValidation Validation required.
	// Solution: Make sure that you don't use a token received with https://vk.com/dev/auth_mobile for a request from the server. It's restricted. The validation process is described on https://vk.com/dev/need_validation.
	//  IsGlobal: true
	Error_AuthValidation ErrorCode = 17
	// Error_UserDeleted User was deleted or banned.
	//  IsGlobal: true
	Error_UserDeleted ErrorCode = 18
	// Error_Blocked Content blocked.
	//  IsGlobal: false
	Error_Blocked ErrorCode = 19
	// Error_MethodPermission Permission to perform this action is denied for non-standalone applications.
	// Solution: If you see this error despite your app has the Standalone type, make sure that you use redirect_uri=https://oauth.vk.com/blank.html. Details here: https://vk.com/dev/auth_mobile.
	//  IsGlobal: true
	Error_MethodPermission ErrorCode = 20
	// Error_MethodAds Permission to perform this action is allowed only for standalone and OpenAPI applications.
	//  IsGlobal: true
	Error_MethodAds ErrorCode = 21
	// Error_Upload Upload error.
	//  IsGlobal: false
	Error_Upload ErrorCode = 22
	// Error_MethodDisabled This method was disabled.
	// Solution: All the methods available now are listed here: https://vk.com/dev/methods.
	//  IsGlobal: true
	Error_MethodDisabled ErrorCode = 23
	// Error_NeedConfirmation Confirmation required.
	// Solution: Confirmation process is described on https://vk.com/dev/need_confirmation.
	//  IsGlobal: true
	Error_NeedConfirmation ErrorCode = 24
	// Error_NeedTokenConfirmation Token confirmation required.
	//  IsGlobal: true
	Error_NeedTokenConfirmation ErrorCode = 25
	// Error_GroupAuth Group authorization failed.
	//  IsGlobal: true
	Error_GroupAuth ErrorCode = 27
	// Error_AppAuth Application authorization failed.
	//  IsGlobal: true
	Error_AppAuth ErrorCode = 28
	// Error_RateLimit Rate limit reached.
	// Solution: More details on rate limits here: https://vk.com/dev/data_limits
	//  IsGlobal: true
	Error_RateLimit ErrorCode = 29
	// Error_PrivateProfile This profile is private.
	//  IsGlobal: true
	Error_PrivateProfile ErrorCode = 30
	// Error_NotImplementedYet Not implemented yet.
	//  IsGlobal: true
	Error_NotImplementedYet ErrorCode = 33
	// Error_ClientVersionDeprecated Client version deprecated.
	//  IsGlobal: true
	Error_ClientVersionDeprecated ErrorCode = 34
	// Error_ClientUpdateNeeded Client update needed.
	//  IsGlobal: false
	Error_ClientUpdateNeeded ErrorCode = 35
	// Error_Timeout Method execution was interrupted due to timeout.
	//  IsGlobal: false
	Error_Timeout ErrorCode = 36
	// Error_UserBanned User was banned.
	//  IsGlobal: true
	Error_UserBanned ErrorCode = 37
	// Error_UnknownApplication Unknown application.
	//  IsGlobal: true
	Error_UnknownApplication ErrorCode = 38
	// Error_UnknownUser Unknown user.
	//  IsGlobal: true
	Error_UnknownUser ErrorCode = 39
	// Error_UnknownGroup Unknown group.
	//  IsGlobal: true
	Error_UnknownGroup ErrorCode = 40
	// Error_AdditionalSignupRequired Additional signup required.
	//  IsGlobal: true
	Error_AdditionalSignupRequired ErrorCode = 41
	// Error_IpIsNotAllowed IP is not allowed.
	//  IsGlobal: true
	Error_IpIsNotAllowed ErrorCode = 42
	// Error_Param One of the parameters specified was missing or invalid.
	// Solution: Check the required parameters list and their format on a method description page.
	//  IsGlobal: true
	Error_Param ErrorCode = 100
	// Error_ParamApiId Invalid application API ID.
	// Solution: Find the app in the administrated list in settings: https://vk.com/apps?act=settings and set the correct API_ID in the request.
	//  IsGlobal: true
	Error_ParamApiId ErrorCode = 101
	// Error_Limits Out of limits.
	// May contain one of the listed subcodes: [ TooManyCommunities ].
	//  IsGlobal: false
	Error_Limits ErrorCode = 103
	// Error_NotFound Not found.
	//  IsGlobal: false
	Error_NotFound ErrorCode = 104
	// Error_SaveFile Couldn't save file.
	//  IsGlobal: false
	Error_SaveFile ErrorCode = 105
	// Error_ActionFailed Unable to process action.
	//  IsGlobal: false
	Error_ActionFailed ErrorCode = 106
	// Error_ParamUserId Invalid user id.
	// Solution: Make sure that you use a correct id. You can get an id using a screen name with the VK.Utils_ResolveScreenName method
	//  IsGlobal: true
	Error_ParamUserId ErrorCode = 113
	// Error_ParamAlbumId Invalid album id.
	//  IsGlobal: false
	Error_ParamAlbumId ErrorCode = 114
	// Error_ParamServer Invalid server.
	//  IsGlobal: false
	Error_ParamServer ErrorCode = 118
	// Error_ParamTitle Invalid title.
	//  IsGlobal: false
	Error_ParamTitle ErrorCode = 119
	// Error_ParamHash Invalid hash.
	//  IsGlobal: false
	Error_ParamHash ErrorCode = 121
	// Error_ParamPhotos Invalid photos.
	//  IsGlobal: false
	Error_ParamPhotos ErrorCode = 122
	// Error_ParamGroupId Invalid group id.
	//  IsGlobal: false
	Error_ParamGroupId ErrorCode = 125
	// Error_ParamPhoto Invalid photo.
	//  IsGlobal: false
	Error_ParamPhoto ErrorCode = 129
	// Error_ParamPageId Page not found.
	//  IsGlobal: false
	Error_ParamPageId ErrorCode = 140
	// Error_AccessPage Access to page denied.
	//  IsGlobal: false
	Error_AccessPage ErrorCode = 141
	// Error_MobileNotActivated The mobile number of the user is unknown.
	//  IsGlobal: false
	Error_MobileNotActivated ErrorCode = 146
	// Error_InsufficientFunds Application has insufficient funds.
	//  IsGlobal: false
	Error_InsufficientFunds ErrorCode = 147
	// Error_ParamTimestamp Invalid timestamp.
	// Solution: You may get a correct value with the VK.Utils_GetServerTime method.
	//  IsGlobal: true
	Error_ParamTimestamp ErrorCode = 150
	// Error_FriendsListId Invalid list id.
	//  IsGlobal: false
	Error_FriendsListId ErrorCode = 171
	// Error_FriendsListLimit Reached the maximum number of lists.
	//  IsGlobal: false
	Error_FriendsListLimit ErrorCode = 173
	// Error_FriendsAddYourself Cannot add user himself as friend.
	//  IsGlobal: false
	Error_FriendsAddYourself ErrorCode = 174
	// Error_FriendsAddInEnemy Cannot add this user to friends as they have put you on their blacklist.
	//  IsGlobal: false
	Error_FriendsAddInEnemy ErrorCode = 175
	// Error_FriendsAddEnemy Cannot add this user to friends as you put him on blacklist.
	//  IsGlobal: false
	Error_FriendsAddEnemy ErrorCode = 176
	// Error_FriendsAddNotFound Cannot add this user to friends as user not found.
	//  IsGlobal: false
	Error_FriendsAddNotFound ErrorCode = 177
	// Error_ParamNoteId Note not found.
	//  IsGlobal: false
	Error_ParamNoteId ErrorCode = 180
	// Error_AccessNote Access to note denied.
	//  IsGlobal: false
	Error_AccessNote ErrorCode = 181
	// Error_AccessNoteComment You can't comment this note.
	//  IsGlobal: false
	Error_AccessNoteComment ErrorCode = 182
	// Error_AccessComment Access to comment denied.
	//  IsGlobal: false
	Error_AccessComment ErrorCode = 183
	// Error_AccessAlbum Access denied.
	// Solution: Make sure you use correct ids (owner_id is always positive for users, negative for communities) and the current user has access to the requested content in the full version of the site.
	//  IsGlobal: true
	Error_AccessAlbum ErrorCode = 200
	// Error_AccessAudio Access denied.
	// Solution: Make sure you use correct ids (owner_id is always positive for users, negative for communities) and the current user has access to the requested content in the full version of the site.
	//  IsGlobal: true
	Error_AccessAudio ErrorCode = 201
	// Error_AccessGroup Access to group denied.
	// Solution: Make sure that the current user is a member or admin of the community (for closed and private groups and events).
	//  IsGlobal: true
	Error_AccessGroup ErrorCode = 203
	// Error_AccessVideo Access denied.
	//  IsGlobal: false
	Error_AccessVideo ErrorCode = 204
	// Error_AccessMarket Access denied.
	//  IsGlobal: false
	Error_AccessMarket ErrorCode = 205
	// Error_WallAccessPost Access to wall's post denied.
	//  IsGlobal: false
	Error_WallAccessPost ErrorCode = 210
	// Error_WallAccessComment Access to wall's comment denied.
	//  IsGlobal: false
	Error_WallAccessComment ErrorCode = 211
	// Error_WallAccessReplies Access to post comments denied.
	//  IsGlobal: false
	Error_WallAccessReplies ErrorCode = 212
	// Error_WallAccessAddReply Access to status replies denied.
	//  IsGlobal: false
	Error_WallAccessAddReply ErrorCode = 213
	// Error_WallAddPost Access to adding post denied.
	//  IsGlobal: false
	Error_WallAddPost ErrorCode = 214
	// Error_WallAdsPublished Advertisement post was recently added.
	//  IsGlobal: false
	Error_WallAdsPublished ErrorCode = 219
	// Error_WallTooManyRecipients Too many recipients.
	//  IsGlobal: false
	Error_WallTooManyRecipients ErrorCode = 220
	// Error_StatusNoAudio User disabled track name broadcast.
	//  IsGlobal: false
	Error_StatusNoAudio ErrorCode = 221
	// Error_WallLinksForbidden Hyperlinks are forbidden.
	//  IsGlobal: false
	Error_WallLinksForbidden ErrorCode = 222
	// Error_WallReplyOwnerFlood Too many replies.
	//  IsGlobal: false
	Error_WallReplyOwnerFlood ErrorCode = 223
	// Error_WallAdsPostLimitReached Too many ads posts.
	//  IsGlobal: false
	Error_WallAdsPostLimitReached ErrorCode = 224
	// Error_WallDonut Donut is disabled.
	//  IsGlobal: false
	Error_WallDonut ErrorCode = 225
	// Error_LikesReactionCanNotBeApplied Reaction can not be applied to the object.
	//  IsGlobal: false
	Error_LikesReactionCanNotBeApplied ErrorCode = 232
	// Error_PollsAccess Access to poll denied.
	//  IsGlobal: false
	Error_PollsAccess ErrorCode = 250
	// Error_PollsPollId Invalid poll id.
	//  IsGlobal: false
	Error_PollsPollId ErrorCode = 251
	// Error_PollsAnswerId Invalid answer id.
	//  IsGlobal: false
	Error_PollsAnswerId ErrorCode = 252
	// Error_PollsAccessWithoutVote Access denied, please vote first.
	//  IsGlobal: false
	Error_PollsAccessWithoutVote ErrorCode = 253
	// Error_AccessGroups Access to the groups list is denied due to the user's privacy settings.
	//  IsGlobal: false
	Error_AccessGroups ErrorCode = 260
	// Error_AlbumFull This album is full.
	// Solution: You need to delete the odd objects from the album or use another album.
	//  IsGlobal: true
	Error_AlbumFull ErrorCode = 300
	// Error_AlbumsLimit Albums number limit is reached.
	//  IsGlobal: false
	Error_AlbumsLimit ErrorCode = 302
	// Error_VotesPermission Permission denied. You must enable votes processing in application settings.
	// Solution: Check the app settings: https://vk.com/editapp?id={Your API_ID}&section=payments
	//  IsGlobal: true
	Error_VotesPermission ErrorCode = 500
	// Error_AdsPermission Permission denied. You have no access to operations specified with given object(s).
	//  IsGlobal: true
	Error_AdsPermission ErrorCode = 600
	// Error_WeightedFlood Permission denied. You have requested too many actions this day. Try later..
	//  IsGlobal: false
	Error_WeightedFlood ErrorCode = 601
	// Error_AdsPartialSuccess Some part of the request has not been completed.
	//  IsGlobal: false
	Error_AdsPartialSuccess ErrorCode = 602
	// Error_AdsSpecific Some ads error occurs.
	//  IsGlobal: true
	Error_AdsSpecific ErrorCode = 603
	// Error_AdsObjectDeleted Object deleted.
	//  IsGlobal: false
	Error_AdsObjectDeleted ErrorCode = 629
	// Error_GroupChangeCreator Cannot edit creator role.
	//  IsGlobal: false
	Error_GroupChangeCreator ErrorCode = 700
	// Error_GroupNotInClub User should be in club.
	//  IsGlobal: false
	Error_GroupNotInClub ErrorCode = 701
	// Error_GroupTooManyOfficers Too many officers in club.
	//  IsGlobal: false
	Error_GroupTooManyOfficers ErrorCode = 702
	// Error_GroupNeed2fa You need to enable 2FA for this action.
	//  IsGlobal: false
	Error_GroupNeed2fa ErrorCode = 703
	// Error_GroupHostNeed2fa User needs to enable 2FA for this action.
	//  IsGlobal: false
	Error_GroupHostNeed2fa ErrorCode = 704
	// Error_GroupTooManyAddresses Too many addresses in club.
	//  IsGlobal: false
	Error_GroupTooManyAddresses ErrorCode = 706
	// Error_GroupAppIsNotInstalledInCommunity Application is not installed in community.
	//  IsGlobal: false
	Error_GroupAppIsNotInstalledInCommunity ErrorCode = 711
	// Error_GroupInviteLinksNotValid Invite link is invalid - expired, deleted or not exists.
	//  IsGlobal: false
	Error_GroupInviteLinksNotValid ErrorCode = 714
	// Error_VideoAlreadyAdded This video is already added.
	//  IsGlobal: false
	Error_VideoAlreadyAdded ErrorCode = 800
	// Error_VideoCommentsClosed Comments for this video are closed.
	//  IsGlobal: false
	Error_VideoCommentsClosed ErrorCode = 801
	// Error_MessagesUserBlocked Can't send messages for users from blacklist.
	//  IsGlobal: false
	Error_MessagesUserBlocked ErrorCode = 900
	// Error_MessagesDenySend Can't send messages for users without permission.
	//  IsGlobal: false
	Error_MessagesDenySend ErrorCode = 901
	// Error_MessagesPrivacy Can't send messages to this user due to their privacy settings.
	//  IsGlobal: false
	Error_MessagesPrivacy ErrorCode = 902
	// Error_MessagesTooOldPts Value of ts or pts is too old.
	//  IsGlobal: false
	Error_MessagesTooOldPts ErrorCode = 907
	// Error_MessagesTooNewPts Value of ts or pts is too new.
	//  IsGlobal: false
	Error_MessagesTooNewPts ErrorCode = 908
	// Error_MessagesEditExpired Can't edit this message, because it's too old.
	//  IsGlobal: false
	Error_MessagesEditExpired ErrorCode = 909
	// Error_MessagesTooBig Can't sent this message, because it's too big.
	//  IsGlobal: false
	Error_MessagesTooBig ErrorCode = 910
	// Error_MessagesKeyboardInvalid Keyboard format is invalid.
	//  IsGlobal: false
	Error_MessagesKeyboardInvalid ErrorCode = 911
	// Error_MessagesChatBotFeature This is a chat bot feature, change this status in settings.
	//  IsGlobal: false
	Error_MessagesChatBotFeature ErrorCode = 912
	// Error_MessagesTooLongForwards Too many forwarded messages.
	//  IsGlobal: false
	Error_MessagesTooLongForwards ErrorCode = 913
	// Error_MessagesTooLongMessage Message is too long.
	//  IsGlobal: false
	Error_MessagesTooLongMessage ErrorCode = 914
	// Error_MessagesChatUserNoAccess You don't have access to this chat.
	//  IsGlobal: false
	Error_MessagesChatUserNoAccess ErrorCode = 917
	// Error_MessagesCantSeeInviteLink You can't see invite link for this chat.
	//  IsGlobal: false
	Error_MessagesCantSeeInviteLink ErrorCode = 919
	// Error_MessagesEditKindDisallowed Can't edit this kind of message.
	//  IsGlobal: false
	Error_MessagesEditKindDisallowed ErrorCode = 920
	// Error_MessagesCantFwd Can't forward these messages.
	//  IsGlobal: false
	Error_MessagesCantFwd ErrorCode = 921
	// Error_MessagesCantDeleteForAll Can't delete this message for everybody.
	//  IsGlobal: false
	Error_MessagesCantDeleteForAll ErrorCode = 924
	// Error_MessagesChatNotAdmin You are not admin of this chat.
	//  IsGlobal: false
	Error_MessagesChatNotAdmin ErrorCode = 925
	// Error_MessagesChatNotExist Chat does not exist.
	//  IsGlobal: false
	Error_MessagesChatNotExist ErrorCode = 927
	// Error_MessagesCantChangeInviteLink You can't change invite link for this chat.
	//  IsGlobal: false
	Error_MessagesCantChangeInviteLink ErrorCode = 931
	// Error_MessagesGroupPeerAccess Your community can't interact with this peer.
	//  IsGlobal: false
	Error_MessagesGroupPeerAccess ErrorCode = 932
	// Error_MessagesChatUserNotInChat User not found in chat.
	//  IsGlobal: false
	Error_MessagesChatUserNotInChat ErrorCode = 935
	// Error_MessagesContactNotFound Contact not found.
	//  IsGlobal: false
	Error_MessagesContactNotFound ErrorCode = 936
	// Error_MessagesMessageRequestAlreadySent Message request already sent.
	//  IsGlobal: false
	Error_MessagesMessageRequestAlreadySent ErrorCode = 939
	// Error_MessagesTooManyPosts Too many posts in messages.
	//  IsGlobal: false
	Error_MessagesTooManyPosts ErrorCode = 940
	// Error_MessagesCantPinOneTimeStory Cannot pin one-time story.
	//  IsGlobal: false
	Error_MessagesCantPinOneTimeStory ErrorCode = 942
	// Error_MessagesIntentCantUse Cannot use this intent.
	//  IsGlobal: false
	Error_MessagesIntentCantUse ErrorCode = 943
	// Error_MessagesIntentLimitOverflow Limits overflow for this intent.
	//  IsGlobal: false
	Error_MessagesIntentLimitOverflow ErrorCode = 944
	// Error_MessagesChatDisabled Chat was disabled.
	//  IsGlobal: false
	Error_MessagesChatDisabled ErrorCode = 945
	// Error_MessagesChatUnsupported Chat not supported.
	//  IsGlobal: false
	Error_MessagesChatUnsupported ErrorCode = 946
	// Error_MessagesMemberAccessToGroupDenied Can't add user to chat, because user has no access to group.
	//  IsGlobal: false
	Error_MessagesMemberAccessToGroupDenied ErrorCode = 947
	// Error_MessagesCantEditPinnedYet Can't edit pinned message yet.
	//  IsGlobal: false
	Error_MessagesCantEditPinnedYet ErrorCode = 949
	// Error_MessagesPeerBlockedReasonByTime Can't send message, reply timed out.
	//  IsGlobal: false
	Error_MessagesPeerBlockedReasonByTime ErrorCode = 950
	// Error_MessagesUserNotDon You can't access donut chat without subscription.
	//  IsGlobal: false
	Error_MessagesUserNotDon ErrorCode = 962
	// Error_MessagesMessageCannotBeForwarded Message cannot be forwarded.
	//  IsGlobal: false
	Error_MessagesMessageCannotBeForwarded ErrorCode = 969
	// Error_MessagesCantPinExpiringMessage Cannot pin an expiring message.
	//  IsGlobal: false
	Error_MessagesCantPinExpiringMessage ErrorCode = 970
	// Error_AuthFloodError Too many auth attempts, try again later.
	//  IsGlobal: false
	Error_AuthFloodError ErrorCode = 1105
	// Error_AuthAnonymousTokenHasExpired Anonymous token has expired.
	//  IsGlobal: true
	Error_AuthAnonymousTokenHasExpired ErrorCode = 1114
	// Error_AuthAnonymousTokenIsInvalid Anonymous token is invalid.
	//  IsGlobal: true
	Error_AuthAnonymousTokenIsInvalid ErrorCode = 1116
	// Error_ParamDocId Invalid document id.
	//  IsGlobal: false
	Error_ParamDocId ErrorCode = 1150
	// Error_ParamDocDeleteAccess Access to document deleting is denied.
	//  IsGlobal: false
	Error_ParamDocDeleteAccess ErrorCode = 1151
	// Error_ParamDocTitle Invalid document title.
	//  IsGlobal: false
	Error_ParamDocTitle ErrorCode = 1152
	// Error_ParamDocAccess Access to document is denied.
	//  IsGlobal: false
	Error_ParamDocAccess ErrorCode = 1153
	// Error_PhotoChanged Original photo was changed.
	//  IsGlobal: false
	Error_PhotoChanged ErrorCode = 1160
	// Error_TooManyLists Too many feed lists.
	//  IsGlobal: false
	Error_TooManyLists ErrorCode = 1170
	// Error_AppsAlreadyUnlocked This achievement is already unlocked.
	//  IsGlobal: false
	Error_AppsAlreadyUnlocked ErrorCode = 1251
	// Error_AppsSubscriptionNotFound Subscription not found.
	//  IsGlobal: false
	Error_AppsSubscriptionNotFound ErrorCode = 1256
	// Error_AppsSubscriptionInvalidStatus Subscription is in invalid status.
	//  IsGlobal: false
	Error_AppsSubscriptionInvalidStatus ErrorCode = 1257
	// Error_InvalidAddress Invalid screen name.
	//  IsGlobal: false
	Error_InvalidAddress ErrorCode = 1260
	// Error_CommunitiesCatalogDisabled Catalog is not available for this user.
	//  IsGlobal: false
	Error_CommunitiesCatalogDisabled ErrorCode = 1310
	// Error_CommunitiesCategoriesDisabled Catalog categories are not available for this user.
	//  IsGlobal: false
	Error_CommunitiesCategoriesDisabled ErrorCode = 1311
	// Error_MarketRestoreTooLate Too late for restore.
	//  IsGlobal: false
	Error_MarketRestoreTooLate ErrorCode = 1400
	// Error_MarketCommentsClosed Comments for this market are closed.
	//  IsGlobal: false
	Error_MarketCommentsClosed ErrorCode = 1401
	// Error_MarketAlbumNotFound Album not found.
	//  IsGlobal: false
	Error_MarketAlbumNotFound ErrorCode = 1402
	// Error_MarketItemNotFound Item not found.
	//  IsGlobal: false
	Error_MarketItemNotFound ErrorCode = 1403
	// Error_MarketItemAlreadyAdded Item already added to album.
	//  IsGlobal: false
	Error_MarketItemAlreadyAdded ErrorCode = 1404
	// Error_MarketTooManyItems Too many items.
	//  IsGlobal: false
	Error_MarketTooManyItems ErrorCode = 1405
	// Error_MarketTooManyItemsInAlbum Too many items in album.
	//  IsGlobal: false
	Error_MarketTooManyItemsInAlbum ErrorCode = 1406
	// Error_MarketTooManyAlbums Too many albums.
	//  IsGlobal: false
	Error_MarketTooManyAlbums ErrorCode = 1407
	// Error_MarketItemHasBadLinks Item has bad links in description.
	//  IsGlobal: false
	Error_MarketItemHasBadLinks ErrorCode = 1408
	// Error_MarketExtendedNotEnabled Extended market not enabled.
	//  IsGlobal: false
	Error_MarketExtendedNotEnabled ErrorCode = 1409
	// Error_MarketGroupingItemsWithDifferentProperties Grouping items with different properties.
	//  IsGlobal: false
	Error_MarketGroupingItemsWithDifferentProperties ErrorCode = 1412
	// Error_MarketGroupingAlreadyHasSuchVariant Grouping already has such variant.
	//  IsGlobal: false
	Error_MarketGroupingAlreadyHasSuchVariant ErrorCode = 1413
	// Error_MarketVariantNotFound Variant not found.
	//  IsGlobal: false
	Error_MarketVariantNotFound ErrorCode = 1416
	// Error_MarketPropertyNotFound Property not found.
	//  IsGlobal: false
	Error_MarketPropertyNotFound ErrorCode = 1417
	// Error_MarketGroupingMustContainMoreThanOneItem Grouping must have two or more items.
	//  IsGlobal: false
	Error_MarketGroupingMustContainMoreThanOneItem ErrorCode = 1425
	// Error_MarketGroupingItemsMustHaveDistinctProperties Item must have distinct properties.
	//  IsGlobal: false
	Error_MarketGroupingItemsMustHaveDistinctProperties ErrorCode = 1426
	// Error_MarketOrdersNoCartItems Cart is empty.
	//  IsGlobal: false
	Error_MarketOrdersNoCartItems ErrorCode = 1427
	// Error_MarketInvalidDimensions Specify width, length, height and weight all together.
	//  IsGlobal: false
	Error_MarketInvalidDimensions ErrorCode = 1429
	// Error_MarketCantChangeVkpayStatus VK Pay status can not be changed.
	//  IsGlobal: false
	Error_MarketCantChangeVkpayStatus ErrorCode = 1430
	// Error_MarketShopAlreadyEnabled Market was already enabled in this group.
	//  IsGlobal: false
	Error_MarketShopAlreadyEnabled ErrorCode = 1431
	// Error_MarketShopAlreadyDisabled Market was already disabled in this group.
	//  IsGlobal: false
	Error_MarketShopAlreadyDisabled ErrorCode = 1432
	// Error_MarketPhotosCropInvalidFormat Invalid image crop format.
	//  IsGlobal: false
	Error_MarketPhotosCropInvalidFormat ErrorCode = 1433
	// Error_MarketPhotosCropOverflow Crop bottom right corner is outside of the image.
	//  IsGlobal: false
	Error_MarketPhotosCropOverflow ErrorCode = 1434
	// Error_MarketPhotosCropSizeTooLow Crop size is less than the minimum.
	//  IsGlobal: false
	Error_MarketPhotosCropSizeTooLow ErrorCode = 1435
	// Error_MarketNotEnabled Market not enabled.
	//  IsGlobal: false
	Error_MarketNotEnabled ErrorCode = 1438
	// Error_MarketAlbumMainHidden Main album can not be hidden.
	//  IsGlobal: false
	Error_MarketAlbumMainHidden ErrorCode = 1446
	// Error_StoryExpired Story has already expired.
	//  IsGlobal: false
	Error_StoryExpired ErrorCode = 1600
	// Error_StoryIncorrectReplyPrivacy Incorrect reply privacy.
	//  IsGlobal: false
	Error_StoryIncorrectReplyPrivacy ErrorCode = 1602
	// Error_PrettyCardsCardNotFound Card not found.
	//  IsGlobal: false
	Error_PrettyCardsCardNotFound ErrorCode = 1900
	// Error_PrettyCardsTooManyCards Too many cards.
	//  IsGlobal: false
	Error_PrettyCardsTooManyCards ErrorCode = 1901
	// Error_PrettyCardsCardIsConnectedToPost Card is connected to post.
	//  IsGlobal: false
	Error_PrettyCardsCardIsConnectedToPost ErrorCode = 1902
	// Error_CallbackApiServersLimit Servers number limit is reached.
	//  IsGlobal: false
	Error_CallbackApiServersLimit ErrorCode = 2000
	// Error_StickersNotPurchased Stickers are not purchased.
	//  IsGlobal: false
	Error_StickersNotPurchased ErrorCode = 2100
	// Error_StickersTooManyFavorites Too many favorite stickers.
	//  IsGlobal: false
	Error_StickersTooManyFavorites ErrorCode = 2101
	// Error_StickersNotFavorite Stickers are not favorite.
	//  IsGlobal: false
	Error_StickersNotFavorite ErrorCode = 2102
	// Error_WallCheckLinkCantDetermineSource Specified link is incorrect (can't find source).
	//  IsGlobal: false
	Error_WallCheckLinkCantDetermineSource ErrorCode = 3102
	// Error_Recaptcha Recaptcha needed.
	//  IsGlobal: true
	Error_Recaptcha ErrorCode = 3300
	// Error_PhoneValidationNeed Phone validation needed.
	//  IsGlobal: true
	Error_PhoneValidationNeed ErrorCode = 3301
	// Error_PasswordValidationNeed Password validation needed.
	//  IsGlobal: true
	Error_PasswordValidationNeed ErrorCode = 3302
	// Error_OtpValidationNeed Otp app validation needed.
	//  IsGlobal: true
	Error_OtpValidationNeed ErrorCode = 3303
	// Error_EmailConfirmationNeed Email confirmation needed.
	//  IsGlobal: true
	Error_EmailConfirmationNeed ErrorCode = 3304
	// Error_AssertVotes Assert votes.
	//  IsGlobal: true
	Error_AssertVotes ErrorCode = 3305
	// Error_TokenExtensionRequired Token extension required.
	//  IsGlobal: true
	Error_TokenExtensionRequired ErrorCode = 3609
	// Error_UserDeactivated User is deactivated.
	//  IsGlobal: true
	Error_UserDeactivated ErrorCode = 3610
	// Error_UserServiceDeactivated Service is deactivated for user.
	//  IsGlobal: true
	Error_UserServiceDeactivated ErrorCode = 3611
	// Error_FaveAliexpressTag Can't set AliExpress tag to this type of object.
	//  IsGlobal: false
	Error_FaveAliexpressTag ErrorCode = 3800
)
